<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFaXjfMw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFaXjfMw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFaXjfMw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFaXjfMw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFaXjfMw\App_KernelDevDebugContainer([
    'container.build_hash' => 'FaXjfMw',
    'container.build_id' => 'bcd8f041',
    'container.build_time' => 1703062172,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFaXjfMw');
