<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerObDutTS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerObDutTS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerObDutTS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerObDutTS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerObDutTS\App_KernelDevDebugContainer([
    'container.build_hash' => 'ObDutTS',
    'container.build_id' => 'faea0fa0',
    'container.build_time' => 1703106127,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerObDutTS');
